# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 19 Apr 2016 20:00:56 +0000
*               @ALL          0
*               @user         8
