version: '2'

volumes:
  dokuwiki_data: {}
  dokuwiki_conf: {}

services:
  dokuwiki:
    image: andrey01/dokuwiki
    network_mode: bridge
    ports:
      - "8080:8080/tcp"
    volumes:
      - dokuwiki_data:/opt/dokuwiki/data
      - dokuwiki_conf:/opt/dokuwiki/conf
